# Generated by Django 5.2.1 on 2025-05-11 01:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model', models.CharField(max_length=50)),
                ('Marka', models.CharField(max_length=50)),
                ('Yil', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)])),
                ('Narx', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(1000)])),
                ('InfoCar', models.TextField(max_length=1000)),
                ('PictureCar', models.ImageField(upload_to='cars_images')),
                ('Stars', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
